name: i_do
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: ^8.3.1
  provider: ^6.1.5+1
  path_provider: ^2.1.5
  path: ^1.8.3
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.3.0
  flutter_md: ^0.0.8
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
